puphpet.ffnord.homepage:
    pattern:  /
    defaults: { _controller: PuphpetMainBundle:ffnord:index }

puphpet.ffnord.vhost:
    pattern:  /vhost
    defaults: { _controller: PuphpetMainBundle:ffnord:vhost }

puphpet.ffnord.directory:
    pattern:  /directory
    defaults: { _controller: PuphpetMainBundle:ffnord:directory }

puphpet.ffnord.files_match:
    pattern:  /files-match
    defaults: { _controller: PuphpetMainBundle:ffnord:filesMatch }
